version: "3.7"
services:
  composer: 
    image: composer
    volumes: 
      - ./app:/app
    command: [tail, -f, /dev/null]
  
  nginx:
    build:
      context: ./nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./app:/app:cached
 
  php:
    build:
      context: ./phpfpm
    volumes:
      - ./app:/app:cached
