version: "3.7"
services:
  composer: 
    image: composer
    volumes: 
      - ./app:/app
    command: [tail, -f, /dev/null]
    working_dir: /app/exam
  
  nginx:
    build:
      context: ./nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./app:/app:cached
    working_dir: /app/exam
   
  node:
    image: node:13
    volumes:
      - ./app:/app:cached
    ports:
      - 3000:3000
    tty: true
    working_dir: /app/exam
 
  php:
    build:
      context: ./phpfpm
    volumes:
      - ./app:/app:cached
    working_dir: /app/exam

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    restart: always
