version: "3.7"
services:
  nginx:
    build:
      context: ./nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./app:/app:cached
    working_dir: /app/exam
   php:
    build:
      context: ./phpfpm
    volumes:
      - ./app:/app:cached
    working_dir: /app/exam