version: "3.7"
services:
  composer:
    image: composer
    volumes:
      - ./src:/app/src:cached
    command: [tail, -f, /dev/null]
    working_dir: /app/src
    environment:
      - CACHE_DRIVER=file

  nginx:
    build:
      context: ./nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./src:/app/src:cached
    working_dir: /app/src

  node:
    image: node:13
    volumes:
      - ./src:/app/src:cached
    ports:
      - 3000:3000
    tty: true
    working_dir: /app/src

  php:
    build:
      context: ./phpfpm
    volumes:
      - ./src:/app/src:cached
    working_dir: /app/src
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=test
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    restart: always
