version: "3.7"
services:
  nginx:
    build:
      context: ./nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./src:/app/src:cached
    working_dir: /app/src
  php:
    build:
      context: ./phpfpm
    volumes:
      - ./src:/app/src:cached
    working_dir: /app/src
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=$DB_HOST
      - DB_PORT=3306
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_BUCKET=$AWS_BUCKET
      - CACHE_DRIVER=memcached
      - SESSION_DRIVER=memcached
      - MEMCACHED_HOST=$MEMCACHED_HOST
      - MEMCACHED_PORT=11211
      - ASSETS_ENDPOINT=$ASSETS_ENDPOINT